Repository pytorch/benchmark, pull requests merged in 2021-04, with the labels that each got.

#335 Add equation_of_state benchmark from pyhpc-benchmarks
  torchbenchmark/models/pyhpc_equation_of_state/__init__.py
  torchbenchmark/models/pyhpc_equation_of_state/eos_pytorch.py
  torchbenchmark/models/pyhpc_equation_of_state/install.py
  torchbenchmark/models/pyhpc_equation_of_state/origin
Labels: cla signed

#336 Add pyhpc-benchmark isoneutral_mixing
  torchbenchmark/models/pyhpc_isoneutral_mixing/__init__.py
  torchbenchmark/models/pyhpc_isoneutral_mixing/install.py
  torchbenchmark/models/pyhpc_isoneutral_mixing/isoneutral_pytorch.py
  torchbenchmark/models/pyhpc_isoneutral_mixing/origin
Labels: cla signed

#351 Added a bunch of transformers from HuggingFace
  torchbenchmark/models/gen_hf_generative.py
  torchbenchmark/models/hf_Albert/__init__.py
  torchbenchmark/models/hf_Albert/install.py
  torchbenchmark/models/hf_Albert/requirements.txt
  torchbenchmark/models/hf_Bart/__init__.py
  torchbenchmark/models/hf_Bart/install.py
  torchbenchmark/models/hf_Bart/requirements.txt
  torchbenchmark/models/hf_Bert/__init__.py
  torchbenchmark/models/hf_Bert/install.py
  torchbenchmark/models/hf_Bert/requirements.txt
  torchbenchmark/models/hf_BigBird/__init__.py
  torchbenchmark/models/hf_BigBird/install.py
  torchbenchmark/models/hf_BigBird/requirements.txt
  torchbenchmark/models/hf_DistilBert/__init__.py
  torchbenchmark/models/hf_DistilBert/install.py
  torchbenchmark/models/hf_DistilBert/requirements.txt
  torchbenchmark/models/hf_GPT2/__init__.py
  torchbenchmark/models/hf_GPT2/install.py
  torchbenchmark/models/hf_GPT2/requirements.txt
  torchbenchmark/models/hf_Longformer/__init__.py
  torchbenchmark/models/hf_Longformer/install.py
  torchbenchmark/models/hf_Longformer/requirements.txt
  torchbenchmark/models/hf_Reformer/__init__.py
  torchbenchmark/models/hf_Reformer/install.py
  torchbenchmark/models/hf_Reformer/requirements.txt
  torchbenchmark/models/hf_T5/__init__.py
  torchbenchmark/models/hf_T5/install.py
  torchbenchmark/models/hf_T5/requirements.txt
Labels: cla signed, hackathon

#343 Increase the batch size from mobilenet training
  torchbenchmark/models/mobilenet_v2/__init__.py
  torchbenchmark/models/mobilenet_v2_quantized_qat/__init__.py
Labels: cla signed, hackathon, hackathon_candidate

#356 Fix HF depedency on datasets
  torchbenchmark/models/gen_hf_generative.py
  torchbenchmark/models/hf_Albert/requirements.txt
  torchbenchmark/models/hf_Bart/requirements.txt
  torchbenchmark/models/hf_Bert/requirements.txt
  torchbenchmark/models/hf_BigBird/requirements.txt
  torchbenchmark/models/hf_DistilBert/requirements.txt
  torchbenchmark/models/hf_GPT2/requirements.txt
  torchbenchmark/models/hf_Longformer/requirements.txt
  torchbenchmark/models/hf_Reformer/requirements.txt
  torchbenchmark/models/hf_T5/requirements.txt
Labels: cla signed

#347 Add run.py driver script and update README
  README.md
  run.py
Labels: cla signed, hackathon

#355 Update ADDING_MODELS.md
  torchbenchmark/models/ADDING_MODELS.md
Labels: cla signed

#357 Fix Circle CI PR correctness check.
  .circleci/config.yml
  scripts/install_cuda.sh
  scripts/install_nightlies.sh
  test.py
Labels: cla signed

#358 Remove warmups in correctness check and run each benchmark only once.
  .circleci/config.yml
  scripts/run_bench_and_upload.sh
Labels: cla signed

#339 Wire callgrind CI into TorchBench harness
  .github/scripts/instr-count-benchmark/config.env
  .github/scripts/instr-count-benchmark/create-nightly-env.sh
  .github/scripts/instr-count-benchmark/run-benchmark.sh
  .github/scripts/instr-count-benchmark/upload.py
Labels: cla signed

#360 point to debug branch for faster testing
  .github/workflows/instruction-count.yml
Labels: cla signed

#352 Add a bunch of timm models.
  requirements.txt
  torchbenchmark/models/gen_timm_models.py
  torchbenchmark/models/timm_efficientnet/__init__.py
  torchbenchmark/models/timm_efficientnet/config.py
  torchbenchmark/models/timm_efficientnet/install.py
  torchbenchmark/models/timm_nfnet/__init__.py
  torchbenchmark/models/timm_nfnet/config.py
  torchbenchmark/models/timm_nfnet/install.py
  torchbenchmark/models/timm_regnet/__init__.py
  torchbenchmark/models/timm_regnet/config.py
  torchbenchmark/models/timm_regnet/install.py
  torchbenchmark/models/timm_resnest/__init__.py
  torchbenchmark/models/timm_resnest/config.py
  torchbenchmark/models/timm_resnest/install.py
  torchbenchmark/models/timm_vision_transformer/__init__.py
  torchbenchmark/models/timm_vision_transformer/config.py
  torchbenchmark/models/timm_vision_transformer/install.py
  torchbenchmark/models/timm_vovnet/__init__.py
  torchbenchmark/models/timm_vovnet/config.py
  torchbenchmark/models/timm_vovnet/install.py
Labels: cla signed

#361 Various fixes to instruction count CI
  .github/scripts/instr-count-benchmark/config.env
  .github/scripts/instr-count-benchmark/create-nightly-env.sh
  .github/scripts/instr-count-benchmark/run-benchmark.sh
  .github/workflows/instruction-count.yml
Labels: cla signed

#363 Add bisection script and devbig local abtest scripts
  .github/scripts/bisection-config.sample.yaml
  .github/scripts/run-bisection.sh
  .github/scripts/run-devbig-abtest.sh
  .github/scripts/run-devbig-stub.sh
  .github/scripts/run-devbig.sh
  bisection.py
  torchbenchmark/__init__.py
  torchbenchmark/util/gitutils.py
Labels: cla signed

#364 Skip models that can not be imported
  torchbenchmark/__init__.py
Labels: cla signed

#366 Add PyTorch PR CI support
  .github/scripts/run-bisection.sh
  bisection.py
  torchbenchmark/util/gitutils.py
Labels: cla signed

#365 Provide more details in local run
  run.py
Labels: cla signed

#367 Fix a bug in the bisector filter.
  bisection.py
Labels: cla signed

#368 Add the runscript of PR test
  .github/scripts/run.sh
  bisection.py
  scripts/run_sweep_existing_envs.sh
Labels: cla signed

#369 Relax the CPU frequency requirement.
  .github/scripts/run.sh
  torchbenchmark/util/machine_config.py
Labels: cla signed
