Repository pytorch/benchmark, pull requests merged in 2021-06, with the labels that each got.

#344 [hackathon] Add differentially-private cifar10 training
  torchbenchmark/models/opacus_cifar10/__init__.py
  torchbenchmark/models/opacus_cifar10/install.py
  torchbenchmark/models/opacus_cifar10/requirements.txt
Labels: cla signed, hackathon, hackathon_candidate

#385 Enable profile directed typing using _script_pdt API
  requirements.txt
  torchbenchmark/models/BERT_pytorch/__init__.py
  torchbenchmark/models/LearningToPaint/__init__.py
  torchbenchmark/models/Super_SloMo/__init__.py
  torchbenchmark/models/attention_is_all_you_need_pytorch/__init__.py
  torchbenchmark/models/attention_is_all_you_need_pytorch/transformer/Models.py
  torchbenchmark/models/demucs/__init__.py
  torchbenchmark/models/densenet121/__init__.py
  torchbenchmark/models/fastNLP/__init__.py
  torchbenchmark/models/fastNLP/fastNLP/models/bert.py
  torchbenchmark/models/pyhpc_equation_of_state/__init__.py
  torchbenchmark/models/pyhpc_isoneutral_mixing/__init__.py
  torchbenchmark/models/pytorch_mobilenet_v3/__init__.py
Labels: cla signed

#386 Add missing task fields to the models
  torchbenchmark/models/mobilenet_v2/__init__.py
  torchbenchmark/models/mobilenet_v2_quantized_qat/__init__.py
  torchbenchmark/models/pyhpc_equation_of_state/__init__.py
  torchbenchmark/models/pyhpc_isoneutral_mixing/__init__.py
Labels: cla signed

#383 run timm models in optimized_for_inference mode
  torchbenchmark/models/gen_timm_models.py
  torchbenchmark/models/timm_efficientnet/__init__.py
  torchbenchmark/models/timm_nfnet/__init__.py
  torchbenchmark/models/timm_regnet/__init__.py
  torchbenchmark/models/timm_resnest/__init__.py
  torchbenchmark/models/timm_vision_transformer/__init__.py
  torchbenchmark/models/timm_vovnet/__init__.py
Labels: cla signed

#346 fix batch sizes
  torchbenchmark/models/BERT_pytorch/__init__.py
  torchbenchmark/models/BERT_pytorch/bert_pytorch/__init__.py
Labels: cla signed, hackathon

#390 freeze LearningToPaint
  torchbenchmark/models/LearningToPaint/__init__.py
Labels: cla signed

#260 add NVFuser
  conftest.py
Labels: cla signed

#391 Add freeze suffix to test names
  test.py
  test_bench.py
  torchbenchmark/models/alexnet/__init__.py
  torchbenchmark/models/densenet121/__init__.py
  torchbenchmark/models/gen_timm_models.py
  torchbenchmark/models/gen_torchvision_benchmarks.py
  torchbenchmark/models/mnasnet1_0/__init__.py
  torchbenchmark/models/mobilenet_v2/__init__.py
  torchbenchmark/models/resnet18/__init__.py
  torchbenchmark/models/resnet50/__init__.py
  torchbenchmark/models/resnext50_32x4d/__init__.py
  torchbenchmark/models/shufflenet_v2_x1_0/__init__.py
  torchbenchmark/models/squeezenet1_1/__init__.py
  torchbenchmark/models/timm_efficientnet/__init__.py
  torchbenchmark/models/timm_nfnet/__init__.py
  torchbenchmark/models/timm_regnet/__init__.py
  torchbenchmark/models/timm_resnest/__init__.py
  torchbenchmark/models/timm_vision_transformer/__init__.py
  torchbenchmark/models/timm_vovnet/__init__.py
  torchbenchmark/models/vgg16/__init__.py
Labels: cla signed

#393 Clean up fuser options
  conftest.py
Labels: cla signed

#392 Enable script_pdt API for torchvision models
  torchbenchmark/models/alexnet/__init__.py
  torchbenchmark/models/densenet121/__init__.py
  torchbenchmark/models/gen_torchvision_benchmarks.py
  torchbenchmark/models/mnasnet1_0/__init__.py
  torchbenchmark/models/mobilenet_v2/__init__.py
  torchbenchmark/models/resnet18/__init__.py
  torchbenchmark/models/resnet50/__init__.py
  torchbenchmark/models/resnext50_32x4d/__init__.py
  torchbenchmark/models/shufflenet_v2_x1_0/__init__.py
  torchbenchmark/models/squeezenet1_1/__init__.py
  torchbenchmark/models/vgg16/__init__.py
Labels: cla signed

#374 Add SpeechTransformer model
  torchbenchmark/models/speech_transformer/__init__.py
  torchbenchmark/models/speech_transformer/config.py
  torchbenchmark/models/speech_transformer/data/__init__.py
  torchbenchmark/models/speech_transformer/data/data.py
  torchbenchmark/models/speech_transformer/input_data/dev/data.json
  torchbenchmark/models/speech_transformer/input_data/dev/feats.1.ark
  torchbenchmark/models/speech_transformer/input_data/lang_1char/train_chars.txt
  torchbenchmark/models/speech_transformer/input_data/test/data.json
  torchbenchmark/models/speech_transformer/input_data/test/feats.1.ark
  torchbenchmark/models/speech_transformer/input_data/train/data.json
  torchbenchmark/models/speech_transformer/input_data/train/feats.1.ark
  torchbenchmark/models/speech_transformer/install.py
  torchbenchmark/models/speech_transformer/requirements.txt
  torchbenchmark/models/speech_transformer/transformer/__init__.py
  torchbenchmark/models/speech_transformer/transformer/attention.py
  torchbenchmark/models/speech_transformer/transformer/decoder.py
  torchbenchmark/models/speech_transformer/transformer/encoder.py
  torchbenchmark/models/speech_transformer/transformer/loss.py
  torchbenchmark/models/speech_transformer/transformer/module.py
  torchbenchmark/models/speech_transformer/transformer/optimizer.py
  torchbenchmark/models/speech_transformer/transformer/transformer.py
  torchbenchmark/models/speech_transformer/utils/__init__.py
  torchbenchmark/models/speech_transformer/utils/data2json.sh
  torchbenchmark/models/speech_transformer/utils/dump.sh
  torchbenchmark/models/speech_transformer/utils/filt.py
  torchbenchmark/models/speech_transformer/utils/json2trn.py
  torchbenchmark/models/speech_transformer/utils/mergejson.py
  torchbenchmark/models/speech_transformer/utils/scp2json.py
  torchbenchmark/models/speech_transformer/utils/text2token.py
  torchbenchmark/models/speech_transformer/utils/utils.py
  torchbenchmark/tasks.py
Labels: cla signed

#394 freeze stargan
  torchbenchmark/models/pytorch_stargan/__init__.py
Labels: cla signed

#387 Add the DrQ model
  torchbenchmark/models/drq/__init__.py
  torchbenchmark/models/drq/config.py
  torchbenchmark/models/drq/drq.py
  torchbenchmark/models/drq/install.py
  torchbenchmark/models/drq/obs.pkl
  torchbenchmark/models/drq/origin
  torchbenchmark/models/drq/replay_buffer.py
  torchbenchmark/models/drq/requirements.txt
  torchbenchmark/models/drq/utils.py
Labels: cla signed

#382 Add Soft Actor Critic (SAC) reinforcement learning model
  torchbenchmark/models/soft_actor_critic/__init__.py
  torchbenchmark/models/soft_actor_critic/config.py
  torchbenchmark/models/soft_actor_critic/envs.py
  torchbenchmark/models/soft_actor_critic/install.py
  torchbenchmark/models/soft_actor_critic/nets.py
  torchbenchmark/models/soft_actor_critic/replay.py
  torchbenchmark/models/soft_actor_critic/requirements.txt
  torchbenchmark/models/soft_actor_critic/sac.py
  torchbenchmark/models/soft_actor_critic/utils.py
Labels: cla signed

#396 Preload the data to train_data in __init__ for Background_Matting
  torchbenchmark/models/Background_Matting/__init__.py
Labels: cla signed

#397 Quantization test model for resnet50
  torchbenchmark/models/resnet50_quantized_qat/__init__.py
  torchbenchmark/models/resnet50_quantized_qat/install.py
Labels: cla signed

#404 Update run.py to warmup and report cuda timings
  run.py
Labels: cla signed

#399 freeze attention
  torchbenchmark/models/attention_is_all_you_need_pytorch/__init__.py
Labels: cla signed

#402 Correcting the casing for PyTorch in README.md
  README.md
Labels: cla signed

#400 Adding TTS Angular Loss Encoder
  requirements.txt
  torchbenchmark/models/tts_angular/__init__.py
  torchbenchmark/models/tts_angular/angular_tts_main.py
  torchbenchmark/models/tts_angular/install.py
  torchbenchmark/models/tts_angular/model.py
  torchbenchmark/models/tts_angular/requirements.txt
Labels: cla signed

#403 NVidia DeepRecommender as Benchmark
  torchbenchmark/models/nvidia_deeprecommender/LICENSE
  torchbenchmark/models/nvidia_deeprecommender/README.md
  torchbenchmark/models/nvidia_deeprecommender/__init__.py
  torchbenchmark/models/nvidia_deeprecommender/compute_RMSE.py
  torchbenchmark/models/nvidia_deeprecommender/data_utils/movie_lense_data_converter.py
  torchbenchmark/models/nvidia_deeprecommender/data_utils/netflix_data_convert.py
  torchbenchmark/models/nvidia_deeprecommender/install.py
  torchbenchmark/models/nvidia_deeprecommender/nvinfer.py
  torchbenchmark/models/nvidia_deeprecommender/nvtrain.py
  torchbenchmark/models/nvidia_deeprecommender/origin
  torchbenchmark/models/nvidia_deeprecommender/reco_encoder/__init__.py
  torchbenchmark/models/nvidia_deeprecommender/reco_encoder/data/__init__.py
  torchbenchmark/models/nvidia_deeprecommender/reco_encoder/data/input_layer.py
  torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/__init__.py
  torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/model.py
  torchbenchmark/models/nvidia_deeprecommender/requirements.txt
Labels: cla signed

#401 Add V1 score
  .circleci/config.yml
  .github/scripts/run.sh
  compute_score.py
  torchbenchmark/models/drq/__init__.py
  torchbenchmark/models/maml_omniglot/__init__.py
  torchbenchmark/models/soft_actor_critic/__init__.py
  torchbenchmark/models/timm_vision_transformer/__init__.py
  torchbenchmark/models/tts_angular/__init__.py
  torchbenchmark/score/compute_score.py
  torchbenchmark/score/compute_score_v0.py
  torchbenchmark/score/compute_score_v1.py
  torchbenchmark/score/configs/v1/config-v1.env
  torchbenchmark/score/configs/v1/config-v1.yaml
  torchbenchmark/score/generate_score_config.py
Labels: cla signed

#408 Fix pytorch_struct broken by more strict in-place operation restrictions
  torchbenchmark/models/pytorch_struct/torch_struct/helpers.py
Labels: cla signed

#407 Add v1 nightly CI workflow
  .github/scripts/run-sweep.sh
  .github/scripts/run.sh
  .github/workflows/v0-nightly.yml
  .github/workflows/v0-sweep.yml
  .github/workflows/v1-nightly.yml
  conftest.py
  scripts/upload_scribe.py
  torchbenchmark/score/compute_score_v1.py
Labels: cla signed

#410 Add other deps to the v1 workflow
  .github/workflows/v1-nightly.yml
Labels: cla signed

#411 Fix CUDA version and the output dir.
  .github/workflows/v1-nightly.yml
Labels: cla signed

#414 Enable the nightly run.
  .github/workflows/v1-nightly.yml
Labels: cla signed

#415 Improve the logs printed by the bisector.
  bisection.py
  requirements.txt
Labels: cla signed

#416 Generate the bisection config and publish to the github actions artifact
  .github/scripts/generate-abtest-config.py
  .github/workflows/v0-bisection.yml
  .github/workflows/v1-bisection.yml
  .github/workflows/v1-nightly.yml
  bisection.py
Labels: cla signed

#418 Add config readme to V1 score
  .github/workflows/v0-nightly.yml
  .github/workflows/v0-sweep.yml
  .github/workflows/v1-nightly.yml
  .github/workflows/v1-sweep.yml
  README.md
  torchbenchmark/score/configs/v1/config-v1.md
Labels: cla signed
